### PR TITLE
Added two characters i've come across a couple of times that should a…

### PR DESCRIPTION
**Pull request by mistenkt**
…lso be sanitized

### CODE REVIEW

**Comment by mistenkt** [comment]
Note that both these characters are actually two characters. It's an a with a circle behind. That in most viewers looks like one character.

**Comment by hiemil** [comment]
It would be real helpful it this got merged.

**Comment by webvitalii** [comment]
Thank you very much for your pull request.
Those symbols (å, Å) already included in the files.
You may find them in the "Extra chars" section.

**Comment by mistenkt** [comment]
The problem is that it is not one character, it is two characters that looks like one.

**Comment by webvitalii** [comment]
Oh, I see now. Got it. Merged.

**Pull request merged**
