### PR TITLE
Remove icons from plugin dashboard

### PR DESCRIPTION
**Pull request by viktorbijlenga**
I would suggest that you remove the icons from the plugins dashboard.

skarmavbild 2016-04-15 kl 10 11 31

### CODE REVIEW

**Comment by viktorbijlenga** [comment]
Ping @webvitalii

**Comment by webvitalii** [comment]
Hi Viktor. Thank you for your PR.
Can you backmerge master branch again? Because your branch has some merge conflicts.

**Comment by viktorbijlenga** [comment]
Yes! I've updated to the latest version and removed the icons from the UI.

**Comment by webvitalii** [comment]
I merged it. I will push it to the main WordPress repo during next plugin update.

**Comment by viktorbijlenga** [comment]
Sounds great! Thanks for a brilliant plugin 😀

**Pull request merged**
